# Generated by Django 4.0.4 on 2022-06-29 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_delete_product_alter_signup_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=10)),
                ('prize', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='product_specs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=0, max_length=2)),
                ('detail', models.TextField(default='', max_length=350)),
                ('product_name', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app1.product')),
            ],
        ),
    ]
