# Generated by Django 4.0.4 on 2022-06-29 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_signup_phone'),
        ('app1', '0004_product_product_specs'),
    ]

    operations = [
    ]
