# Generated by Django 4.0.4 on 2022-06-29 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_merge_20220629_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='prize',
        ),
        migrations.AddField(
            model_name='product',
            name='des',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='review',
            field=models.TextField(default='', max_length=350),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='signup',
            name='phone',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='product_specs',
        ),
    ]
