# Generated by Django 4.0.4 on 2022-07-08 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_signup_is_a_vendor_alter_product_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='is_a_vendor',
            new_name='vendor',
        ),
    ]
